version: '1.0'

jobs:

  runs-on: java-ci-base2:latest

  setup:
    steps:
      - name: Clean Workspace
        run: rm -rf workspace/app

      - name: Clone Repository
        run: git clone https://github.com/Sectani/gradle-app workspace/app

  test:
    depends-on: setup
    steps:
      - name: Run Tests
        working-directory: workspace/app/project
        run: |
          ./gradlew test
          mkdir -p /artifacts/test-reports
          cp -r build/test-results/test/* /artifacts/test-reports/

  build:
    depends-on: test
    steps:
      - name: Build Project
        working-directory: workspace/app/project
        run: ./gradlew build -x test

      - name: Save Artifacts
        run: cp build/libs/*.jar /artifacts/

  docker_push:
    depends-on: build
    steps:
      - name: Build Docker Image
        working-directory: workspace/app/project
        run: docker build -t sectani/gradle-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_EAMIL" --password-stdin

      - name: Push Docker Image
        run: docker push sectani/gradle-app:latest
